### ISSUE TITLE
Theme pick list should close when you click outside the box

### ISSUE THREAD

**Issue by l4ur4oliveira** [l4ur4oliveira/hacktober-calc#1]
We need to improve the theme selection behavior.
The list will only close when you click "Theme" button again or when you select an item.

![image](https://user-images.githubusercontent.com/4943158/194168858-dc00d9e3-a16f-4e78-a080-4e79125eb137.png)

**Comment by djanilsonBarista** [comment]
Hi!?
Can I work on this !?

**Comment by l4ur4oliveira** [comment]
Sure! 😊

**Comment by om-ghumare** [comment]
any updates? or should i do the pr for same??

**Comment by l4ur4oliveira** [comment]
Closing :)
