### ISSUE TITLE
Z-index dropdown problem

### ISSUE THREAD

**Issue by l4ur4oliveira** [l4ur4oliveira/hacktober-calc#17]
As the number of themes increased, I noticed that the buttons are overlapping the dropdown menu on hover.

![image](https://user-images.githubusercontent.com/4943158/194711111-4800887c-821c-4532-ba76-99d52260a70a.png)

**Comment by amitroy-thedev** [comment]
Hey @l4ur4oliveira assign me this project..

**Comment by amitroy-thedev** [comment]
hey @l4ur4oliveira the z-index is already fixed on what issue i should work on ?

**Comment by amitroy-thedev** [comment]
Hi @l4ur4oliveira i need some help actually i forked your project but after cloning on my localhost the functions are not working

**Comment by l4ur4oliveira** [comment]
Hi @amitroy-thedev,
What functions don't work?
I took a look at your fork and your project is 2 commits behind.
Maybe you need to update it.

**Comment by amitroy-thedev** [comment]
I've update that but still the functions are not working..
i think probably the javascript is not working or is not linked with html file

**Comment by l4ur4oliveira** [comment]
Hi @amitroy-thedev, you need to use Live Server to run the HTML.
If you just open the file in the browser you'll have a CORS issue.

**Comment by amitroy-thedev** [comment]
Okay ..Let me try that

**Comment by amitroy-thedev** [comment]
Hi @l4ur4oliveira
The z-index problem solved their was only one line of css code in regarding of z-index which i added so i thought it was a little contribuiton so i also added a new vintage theme..hope you'll like that

**Comment by amitroy-thedev** [comment]
#18
