### ISSUE TITLE
Restrict the use of math operators while an operation is ongoing

### ISSUE THREAD

**Issue by carlospatinos** [l4ur4oliveira/hacktober-calc#22]
This will help with scenarios when an ongoing operation is in progress

Such as 
1- click any number
2- click an operation (+,-,/,*)
3- As of now you can keep clicking operations (which is not correct) so if we stop the use of those operators, a number has to be selected and then = to reenable those operators

**Comment by l4ur4oliveira** [comment]
Hi @carlospatinos,
I could not reproduce this problem. Could you attach a print or give more details?

**Comment by carlospatinos** [comment]
@l4ur4oliveira 
Try this:
3*3*4=
On the screen you can see the whole operation but in the result you can only see the result for the first 2 operands (3*3)=9
So I read the code and you are only allowing operations between 2 numbers (i think) so I went and disabled the operations after one operation is selected now with this code change you can only do 
3*3
If you try to add another operator (-,*,/) i will not click keeping the calculator consistent for now until you decide to support concatenation of operands

I hope this make sense, please let me know if this is not clear enough

**Comment by l4ur4oliveira** [comment]
Got it! In fact, the calculation happens with the last two numbers.
Your solution is ok but it needs some adjustments.
I'll show you in code review. 😉

**Comment by carlospatinos** [comment]
I will work on that then as you suggested ! Thanks
