### ISSUE TITLE
Calculations with decimal numbers don't work

### ISSUE THREAD

**Issue by l4ur4oliveira** [l4ur4oliveira/hacktober-calc#8]
Floating numbers must be handle properly.

Some test cases:

1. `2 + .2 = NaN`
2. `0.1 + 1 = equals button doesn't work`
3. `1.2 + 0.8 = 1`
4. `0.8 + 1.2 = same as 2`

**Comment by ProtyayMnd50** [comment]
Can you assign me this issue @l4ur4oliveira ? I can give it a try

**Comment by l4ur4oliveira** [comment]
Hi @ProtyayMnd50. Here it is! 😊

**Comment by Harikrishna3** [comment]
I'd like to work on this;
 Would you kindly assign it to me?

**Comment by sankave00** [comment]
> Floating numbers must be handle properly.
> 
> Some test cases:
> 
> 1. `2 + .2 = NaN`
> 2. `0.1 + 1 = equals button doesn't work`
> 3. `1.2 + 0.8 = 1`
> 4. `0.8 + 1.2 = same as 2`

I would like to work on this..could you please assign me this and add the hacktoberfest tag

**Comment by l4ur4oliveira** [comment]
Hi @sankave00,
I believe that @Harikrishna3 has the preference. Would you still like to work on it @Harikrishna3?

Let us know! 😉

**Comment by kumarAbhinav919** [comment]
if it is still available please let me know.

**Comment by Harikrishna3** [comment]
> Hi @sankave00, I believe that @Harikrishna3 has the preference. Would you still like to work on it @Harikrishna3?
> 
> Let us know! 😉

sure I will try

**Comment by Harikrishna3** [comment]
Even buttons are not working, properly. It doesn't show in screen.

**Comment by Harikrishna3** [comment]
![image](https://user-images.githubusercontent.com/86600101/194713547-ebc17545-8323-4fcf-ac86-ab9902f45935.png)

**Comment by Harikrishna3** [comment]
> Even buttons are not working, properly. It doesn't show in screen.

![image](https://user-images.githubusercontent.com/86600101/194713581-2979eb93-851f-4b74-9ee2-0006470e6332.png)

**Comment by l4ur4oliveira** [comment]
Hi @Harikrishna3, you need to use Live Server to run the HTML.
If you run it locally you'll have a CORS issue.
