### ISSUE TITLE
Adding keyboard function

### ISSUE THREAD

**Issue by OgunmisiM** [l4ur4oliveira/hacktober-calc#9]
what about if keypress is allowed for the project. using the keyboard makes it easier to use

**Comment by Harikrishna3** [comment]
I'd like to work on this, Would you kindly assign it to me? and also label hacktoberfest plz.

**Comment by l4ur4oliveira** [comment]
Hi @OgunmisiM. Good idea! Would you like to work on it?

**Comment by OgunmisiM** [comment]
Sure that will be great.
